import type { User, Department, Consultation, NewsArticle, Donation, Testimonial } from './types';
import { PlaceHolderImages } from './placeholder-images';

const getImage = (id: string) => PlaceHolderImages.find(img => img.id === id)?.imageUrl || '';

export const users: User[] = [
  { 
    id: 'user-1', 
    fullName: 'Sarah Day', 
    email: 'sarah.day@example.com', 
    role: 'student', 
    avatarUrl: getImage('avatar-1'), 
    active: true,
    phoneNumber: '123-456-7890',
    motherChurch: 'Central Church',
    entryYear: '2020',
    departmentName: 'Computer Science',
    schoolLevel: 'Fourth Year',
    graduationYear: '2024',
    studentStatus1: 'Regular',
    studentStatus2: 'Degree Program',
    studentStatus3: 'Current WPCM',
    talents: ['Song', 'Leadership'],
    specialCare: ['Consultation Support'],
  },
  { 
    id: 'user-2', 
    fullName: 'John Smith', 
    email: 'john.smith@example.com', 
    role: 'student', 
    avatarUrl: getImage('avatar-2'), 
    active: true,
    phoneNumber: '234-567-8901',
    motherChurch: 'Hilltop Chapel',
    entryYear: '2021',
    departmentName: 'Engineering',
    schoolLevel: 'Third Year',
    graduationYear: '2025',
    studentStatus1: 'Regular',
    studentStatus2: 'Degree Program',
    studentStatus3: 'Current WPCM',
    talents: ['Preach'],
    specialCare: [],
  },
  { 
    id: 'user-3', 
    fullName: 'Maria Garcia', 
    email: 'maria.garcia@example.com', 
    role: 'student', 
    avatarUrl: getImage('avatar-3'), 
    active: false,
    phoneNumber: '345-678-9012',
    motherChurch: 'Riverside Assembly',
    entryYear: '2019',
    departmentName: 'Medicine',
    schoolLevel: 'Fifth Year',
    graduationYear: '2026',
    studentStatus1: 'Irregular (Private)',
    studentStatus2: 'Degree Program',
    studentStatus3: 'Alumni WPCM',
    talents: ['Decorations', 'Media & Communication'],
    specialCare: ['Financial Support'],
  },
  { 
    id: 'user-4', 
    fullName: 'Dr. Emily White', 
    email: 'emily.white@example.com', 
    role: 'consultant', 
    departmentId: 'dept-3', 
    avatarUrl: getImage('avatar-4'), 
    active: true,
    phoneNumber: '456-789-0123',
    motherChurch: 'Central Church',
    entryYear: 'N/A',
    departmentName: 'Medical',
    schoolLevel: 'Seventh Year',
    graduationYear: 'N/A',
    studentStatus1: 'Regular',
    studentStatus2: 'MS Program',
    studentStatus3: 'Alumni WPCM',
    talents: [],
    specialCare: [],
  },
  { 
    id: 'user-5', 
    fullName: 'Pastor Michael Brown', 
    email: 'michael.brown@example.com', 
    role: 'consultant', 
    departmentId: 'dept-1', 
    avatarUrl: getImage('avatar-5'), 
    active: true,
    phoneNumber: '567-890-1234',
    motherChurch: 'Central Church',
    entryYear: 'N/A',
    departmentName: 'Spiritual Counseling',
    schoolLevel: 'Seventh Year',
    graduationYear: 'N/A',
    studentStatus1: 'Regular',
    studentStatus2: 'MS Program',
    studentStatus3: 'Alumni WPCM',
    talents: ['Preach', 'Leadership'],
    specialCare: [],
  },
  { 
    id: 'user-6', 
    fullName: 'Jessica Jones', 
    email: 'jessica.jones@example.com', 
    role: 'admin', 
    avatarUrl: getImage('avatar-6'), 
    active: true,
    phoneNumber: '678-901-2345',
    motherChurch: 'N/A',
    entryYear: 'N/A',
    departmentName: 'Administration',
    schoolLevel: 'Seventh Year',
    graduationYear: 'N/A',
    studentStatus1: 'Regular',
    studentStatus2: 'MS Program',
    studentStatus3: 'Alumni WPCM',
    talents: [],
    specialCare: [],
  },
  { 
    id: 'user-7', 
    fullName: 'David Lee', 
    email: 'david.lee@example.com', 
    role: 'consultant', 
    departmentId: 'dept-2', 
    avatarUrl: 'https://picsum.photos/seed/avatar7/100/100', 
    active: true,
    phoneNumber: '789-012-3456',
    motherChurch: 'Hilltop Chapel',
    entryYear: 'N/A',
    departmentName: 'Psychology',
    schoolLevel: 'Seventh Year',
    graduationYear: 'N/A',
    studentStatus1: 'Regular',
    studentStatus2: 'MS Program',
    studentStatus3: 'Alumni WPCM',
    talents: ['Leadership'],
    specialCare: [],
  },
  { 
    id: 'user-8', 
    fullName: 'Laura Martinez', 
    email: 'laura.martinez@example.com', 
    role: 'consultant', 
    departmentId: 'dept-4', 
    avatarUrl: 'https://picsum.photos/seed/avatar8/100/100', 
    active: false,
    phoneNumber: '890-123-4567',
    motherChurch: 'Riverside Assembly',
    entryYear: 'N/A',
    departmentName: 'Marriage & Family',
    schoolLevel: 'Seventh Year',
    graduationYear: 'N/A',
    studentStatus1: 'Regular',
    studentStatus2: 'MS Program',
    studentStatus3: 'Alumni WPCM',
    talents: [],
    specialCare: [],
  },
];

export const departments: Department[] = [
  { id: 'dept-1', name: 'Spiritual Counseling', description: 'Guidance and support for spiritual questions and growth.' },
  { id: 'dept-2', name: 'Psychology', description: 'Professional help for mental and emotional well-being.' },
  { id: 'dept-3', name: 'Medical', description: 'Consultations with certified medical professionals.' },
  { id: 'dept-4', name: 'Marriage & Family', description: 'Support for couples and families navigating challenges.' },
  { id: 'dept-5', name: 'Youth & Career', description: 'Mentorship for young people on life and career paths.' },
  { id: 'dept-6', name: 'Addiction Recovery', description: 'A safe space and guidance for overcoming addiction.' },
];

export const consultations: Consultation[] = [
  {
    id: 'cons-1',
    studentId: 'user-1',
    consultantId: 'user-5',
    departmentId: 'dept-1',
    problemDescription: 'Feeling distant from God and struggling with prayer life. Need guidance on how to reconnect.',
    preferredTime: 'Weekday evenings',
    status: 'ACTIVE',
    createdAt: '2023-10-26T10:00:00Z',
    lastMessageAt: '2023-11-15T14:30:00Z',
    messages: [
      { id: 'msg-1-1', senderId: 'user-1', text: 'Hello Pastor Michael, I\'m really struggling with my faith lately.', timestamp: '2023-10-26T10:05:00Z' },
      { id: 'msg-1-2', senderId: 'user-5', text: 'Hello Sarah, thank you for reaching out. Tell me more about what you\'re feeling.', timestamp: '2023-10-26T11:20:00Z' },
      { id: 'msg-1-3', senderId: 'user-1', text: 'It feels like my prayers are empty and I\'m just going through the motions.', timestamp: '2023-10-27T09:00:00Z' },
      { id: 'msg-1-4', senderId: 'user-5', text: 'That\'s a common feeling. Let\'s explore some ways to refresh your spiritual practices together.', timestamp: '2023-10-27T10:15:00Z' },
    ],
  },
  {
    id: 'cons-2',
    studentId: 'user-2',
    departmentId: 'dept-2',
    problemDescription: 'Experiencing high levels of anxiety and stress from work. It\'s affecting my sleep and daily life.',
    preferredTime: 'Weekends',
    status: 'PENDING',
    createdAt: '2023-11-14T11:00:00Z',
    messages: [],
  },
  {
    id: 'cons-3',
    studentId: 'user-3',
    consultantId: 'user-4',
    departmentId: 'dept-3',
    problemDescription: 'I have some questions about a minor health issue and would like a professional opinion before seeing a doctor in person.',
    preferredTime: 'Anytime',
    status: 'COMPLETED',
    createdAt: '2023-09-01T15:00:00Z',
    lastMessageAt: '2023-09-05T18:00:00Z',
    messages: [],
  },
  {
    id: 'cons-4',
    studentId: 'user-1',
    consultantId: 'user-7',
    departmentId: 'dept-2',
    problemDescription: 'I think I might be dealing with burnout from my studies and part-time job.',
    preferredTime: 'Weekday evenings',
    status: 'ASSIGNED',
    createdAt: '2023-11-16T09:00:00Z',
    messages: [],
  },
   {
    id: 'cons-5',
    studentId: 'user-3',
    consultantId: 'user-8',
    departmentId: 'dept-4',
    problemDescription: 'Long-standing communication issues with my spouse. We need guidance.',
    preferredTime: 'Weekends',
    status: 'PAUSED',
    createdAt: '2023-08-01T10:00:00Z',
    lastMessageAt: '2023-10-01T12:00:00Z',
    messages: [],
  },
];

export const news: NewsArticle[] = [
  { id: 'news-1', title: 'Annual Community Picnic Next Saturday!', content: 'Join us for a day of fun, food, and fellowship at our annual community picnic. All are welcome! We will have games for kids, a barbecue, and live music. The event starts at 11 AM at Central Park. We hope to see you there!', imageUrl: getImage('news-1'), publishedAt: '2023-11-10', author: 'Jane Doe' },
  { id: 'news-2', title: 'New Youth Group Leadership Program', content: 'We are excited to launch a new leadership program for our youth group members aged 14-18. This program will focus on developing skills in communication, teamwork, and service. Sign-ups are open until the end of the month.', imageUrl: getImage('news-2'), publishedAt: '2023-11-05', author: 'John Davis' },
  { id: 'news-3', title: 'Call for Volunteers for the Winter Shelter', content: 'As the weather gets colder, our local winter shelter needs more hands. We are looking for volunteers to help with meal service, cleaning, and administrative tasks. Your support can make a huge difference.', imageUrl: getImage('news-3'), publishedAt: '2023-11-01', author: 'Admin' },
];

export const donations: Donation[] = [
    { id: 'don-1', name: 'Anonymous', email: 'anon@example.com', amount: 50, date: '2023-11-12' },
    { id: 'don-2', name: 'Mark Johnson', email: 'mark.j@example.com', amount: 100, date: '2023-11-10' },
    { id: 'don-3', name: 'Susan Williams', email: 's.williams@example.com', amount: 25, date: '2023-11-08' },
];

export const testimonials: Testimonial[] = [
  {
    id: 'test-1',
    name: 'John D.',
    role: 'Student',
    quote: 'This platform was a lifeline for me during a really tough semester. The guidance I received was compassionate, practical, and helped me find my footing again. I am incredibly grateful.',
    avatarUrl: getImage('testimonial-1')
  },
  {
    id: 'test-2',
    name: 'Sarah K.',
    role: 'Recent Graduate',
    quote: 'I was struggling with career decisions, and the mentorship I found here was invaluable. Speaking to a professional in my field who shared my values made all the difference.',
    avatarUrl: getImage('testimonial-2')
  },
  {
    id: 'test-3',
    name: 'Michael P.',
    role: 'Community Member',
    quote: 'The spiritual counseling provided clarity and peace during a difficult family situation. It\'s a blessing to have such a confidential and caring resource within our church community.',
    avatarUrl: getImage('testimonial-3')
  }
];
